### ISSUE TITLE
Bindables reference problem .NET Framework 4.7.1

### ISSUE THREAD

**Issue by AsValeO** [notanaverageman/Bindables#11]
Issue appeared after Bindables updated to 0.6.0 and some other packages updated.
Each time after .NET Framework 4.7.1 WPF class library project closed and than opened VS as well as Resharper cannot resolve Bindables reference.
After uninstall and then install Bindables, Resharper build successfully resolve reference and can build the project, VS build still cannot resolve reference and build the project.

**Comment by notanaverageman** [comment]
I have seen that exact problem in one of my projects as well. I think Fody package has broken something.
I tried two things and one of them fixed the issue (I don't remember which one):
 - Updating Fody.
 - Removing `<Private>True</Private>` entry from the Bindables package reference in .csproj file.

**Comment by AsValeO** [comment]
Unfortunately both installing different versions of Fody and removing `<PrivateAssets>all</PrivateAssets>` from .csproj not solved the problem.

**Comment by notanaverageman** [comment]
I have tried the issue with a clean project and deleting the following line from .csproj file fixed the issue:

`<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>`

I don't know why this line is causing problems. I haven't changed any NuGet configuration for a long time. I will release an update when I find and fix the issue.

**Comment by AsValeO** [comment]
Issue solved. Please, notify when this line can be returned.

**Comment by notanaverageman** [comment]
This issue is not as simple as I thought. Underlying cause can be seen [here](https://github.com/NuGet/Home/issues/7084).

As far as I can see Fody plugins has changed the way NuGet package is created and it requires some other changes to code since the project references are reversed. I will try to find a better solution. If I cannot, then I can follow the same path as the other plugins.

**Comment by notanaverageman** [comment]
Fixed as of Bindables version 4.0.0.

**Comment by AsValeO** [comment]
Hmm. In my case issue appeared again with v4.0.0.
In v0.6.0 the project built successfully with `<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>` line deleted. Now line missing and cannot build project again.
VS2019/.NET Core 3.0 preview.

**Comment by notanaverageman** [comment]
There was some problems with packaging, so I had to do it manually and didn't reference Fody. I will add the dependency.

I have released the package only for .NET Framework. There is no weaver for .NET Core for now as it is in preview. You can open another issue for .NET Core support.
