### ISSUE TITLE
.NET 4.5.2 compatibility

### ISSUE THREAD

**Issue by VidVid** [notanaverageman/Bindables#12]
It would be helpful if this could target .net 4.5.2. Is there any reason that the target framework can't be changed from 4.6 to 4.5.2?
The project was still able to build and pass the tests locally for me by simply changing the target framework for Bindables.csproj, but I don't know enough about weaver development to know if there are other gotchas in the pipeline.

**Comment by notanaverageman** [comment]
I tried it with 4.5.2 and it seems to work. There is another issue with NuGet packaging. I will try to release a package after fixing it.

**Comment by notanaverageman** [comment]
Fixed as of Bindables version 4.0.0.
