### ISSUE TITLE
Bindables v4.0.0 reference problem .NET Core 3.0 preview

### ISSUE THREAD

**Issue by AsValeO** [notanaverageman/Bindables#15]
Hmm. In my case issue #11 appeared again with v4.0.0.
In v0.6.0 the project built successfully with 
`<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>`
 line deleted. Now line missing after package updated and cannot build project again.
VS2019/.NET Core 3.0 preview.
Why Bindables package has no dependency on Fody? Is it okay?
**UPD:**
Please, add .NET Core support.
#11 behaviour was the same both in .NET Framework 4.7.1 and in .NET Core 3.0 - Bindables worked with  the line deleted.

**Comment by AsValeO** [comment]
I use 4 other weavers in my solution, and all of them works well both in Framework and in Core. Nothing changed after migration. This problem appears only in Bindables and I bet if I switch back to .NET Framework the problem in v4.0.0 will not disappear. Bindables is great, very useful for me . I hope it will be fixed.

**Comment by AsValeO** [comment]
I use 4 other weavers in my solution, and all of them works well both in Framework and in Core. Nothing changed after migration. This problem appears only in Bindables and I bet if I switch back to .NET Framework the problem in v4.0.0 will not disappear. Bindables is great, very useful for me. I hope it will be fixed.

**Comment by AsValeO** [comment]
Please, take a look at this issue. Our development is almost stopped because project cannot build with new Bindables version.

**Comment by notanaverageman** [comment]
Should be resolved with 6.0.0.
