### ISSUE TITLE
Update needed to work with fody 6.0+

### ISSUE THREAD

**Issue by PrimaForge** [notanaverageman/Bindables#18]
Update needed to work with fody 6.0+

**Comment by notanaverageman** [comment]
Next version will probably be without Fody. https://github.com/yusuf-gunaydin/Bindables/issues/17#issuecomment-524630384

**Comment by notanaverageman** [comment]
Updated to Fody 6.0.0. Roslyn code generation works only on SDK style projects and the main target of this project is still the users using the old project format.
