### ISSUE TITLE
Code generation not worked

### ISSUE THREAD

**Issue by Int32Overflow** [notanaverageman/Bindables#19]
The decompiled source code still contains the attribute `[DependencyProperty]` and no DependencyProperty was created automatically. I'm using the latest version without Fody and so I didn't create "FodyWeavers.xml".
I didn't see any messages while building.

What have I done wrong? Thank you very much in advance.

**Screenshot from IlSpy:**
![grafik](https://user-images.githubusercontent.com/20139038/64847027-54141800-d60e-11e9-983b-c3a0bc40a615.png)

**I'm using:**

- Visual Studio 2019 Enterprise (x64)
- .NET Framework 4.6.1

**Comment by notanaverageman** [comment]
Did you add `<Bindables />` to FodyWeavers.xml?

**Comment by Int32Overflow** [comment]
@yusuf-gunaydin  Do I still need the FodyWeavers.xml even if no Fody is used anymore? This is confusing....

**Comment by notanaverageman** [comment]
This project is a plugin for Fody. So you have to use Fody.

**Comment by Int32Overflow** [comment]
Okay. Because there are no Fody dependencies in the nuget-package. I got it wrong. I thought you already switched to Roslyn.

Which fody-version should I use?

**Comment by Int32Overflow** [comment]
Thank you for your fast response 👍

**Comment by Int32Overflow** [comment]
Now it works perfekt 👍 
Thank you very much. Sorry for my stupidity...

**Comment by notanaverageman** [comment]
It should be Fody 4.x.

There must be a problem with NuGet package then. But, I don't think I will spend time fixing it since I am already planning to switch to Roslyn anyways.
