### ISSUE TITLE
Error when trying to run tests dependant on libs using Bindables

### ISSUE THREAD

**Issue by SingThatSong** [notanaverageman/Bindables#20]
I have a .NET Core 3.1 WPF app, which is using Bindables.
When I'm trying to run tests using 'dotnet test' on a test project, which have a reference to the main project. I get the following error:

> Could not find file '%User_Folder%\.nuget\packages\bindables.fody\6.0.0\Bindables.Fody.dll'

There is a file in netclassicweaver subfolder, but when I copy it to the required destination, I get the following error:

> MSBUILD : error : Fody: An unhandled exception occurred: [%MyProject.cshtml_Path%]
> MSBUILD : error : Exception: [%MyProject.cshtml_Path%]
> MSBUILD : error : Failed to execute weaver C:\Users\maxim\.nuget\packages\bindables.fody\6.0.0\build\..\\Bindables.Fody.dll [%MyProject.cshtml_Path%]
> MSBUILD : error : Type: [%MyProject.cshtml_Path%]
> MSBUILD : error : System.Exception [%MyProject.cshtml_Path%]
> MSBUILD : error : StackTrace: [%MyProject.cshtml_Path%]
> MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\Myprojects\fody\FodyIsolated\InnerWeaver.cs:line 210 [%MyProject.cshtml_Path%]
> MSBUILD : error :    at InnerWeaver.Execute() in C:\Myprojects\fody\FodyIsolated\InnerWeaver.cs:line 111 [%MyProject.cshtml_Path%]
> MSBUILD : error : Source: [%MyProject.cshtml_Path%]
> MSBUILD : error : FodyIsolated [%MyProject.cshtml_Path%]
> MSBUILD : error : TargetSite: [%MyProject.cshtml_Path%]
> MSBUILD : error : Void ExecuteWeavers() [%MyProject.cshtml_Path%]
> MSBUILD : error : Could not load type 'System.Windows.DependencyPropertyKey' from assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. [%MyProject.cshtml_Path%]
> MSBUILD : error : Type: [%MyProject.cshtml_Path%]
> MSBUILD : error : System.TypeLoadException [%MyProject.cshtml_Path%]
> MSBUILD : error : StackTrace: [%MyProject.cshtml_Path%]
> MSBUILD : error :    at Bindables.Fody.DependencyPropertyWeaver..ctor(ModuleDefinition moduleDefinition) [%MyProject.cshtml_Path%]
> MSBUILD : error :    at Bindables.Fody.ModuleWeaver.Execute() [%MyProject.cshtml_Path%]
> MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\Myprojects\fody\FodyIsolated\InnerWeaver.cs:line 198 [%MyProject.cshtml_Path%]
> MSBUILD : error : Source: [%MyProject.cshtml_Path%]
> MSBUILD : error : Bindables.Fody [%MyProject.cshtml_Path%]
> MSBUILD : error : TargetSite: [%MyProject.cshtml_Path%]
> MSBUILD : error : Void .ctor(Mono.Cecil.ModuleDefinition) [%MyProject.cshtml_Path%]
> MSBUILD : error :  [%MyProject.cshtml_Path%]

**Comment by notanaverageman** [comment]
I have rewritten the project as a Roslyn source generator. Please open a new issue if this is still a problem.
