### ISSUE TITLE
Support for `CoerceValueCallback` in Source Generator

### ISSUE THREAD

**Issue by Nextra** [notanaverageman/Bindables#23]
The Fody variant of this package is marked as deprecated on NuGet, but it seems like the Source Generator version can not yet replace all usage scenarios, as there is currently no support for `CoerceValueCallback`/`OnCoerceValue`. 

Would be great if the new package had feature parity, or an alternative/workaround was acknowledged in the `README`.

**Comment by notanaverageman** [comment]
You can always use the standard WPF way of defining dependency properties.
Also a PR is always welcome.

**Comment by Nextra** [comment]
@notanaverageman  I've never worked with Source Generators before, but I made an attempt #24.
