### ISSUE TITLE
Error: Out of date version of Mono.Cecil.dll

### ISSUE THREAD

**Issue by RR-345** [notanaverageman/Bindables#4]
Hello, 
When installing this extension....I get the error below when rebuilding project.  Is there any way to fix it?  I tried current and prior versions, but the error pops up every time.  Thanks.  

Fody: The weaver assembly 'Bindables.Fody, Version=0.3.1.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.

**Comment by notanaverageman** [comment]
You are probably using Fody 2.0. Can you downgrade it to 1.29.4? Fody has done some breaking changes, but I haven't got the time to update this library.

**Comment by notanaverageman** [comment]
I have published the 0.4.0 version with Fody 2.0 dependency to Nuget. Does it solve your problem?

**Comment by RR-345** [comment]
Hey Yusuf,
I just tested it, works perfect!  Many thanks.  Such a helpful library....
