### ISSUE TITLE
Update to fody 3.0

### ISSUE THREAD

**Issue by PrimaForge** [notanaverageman/Bindables#5]
Could we get this updated to the latest Fody 3.0 version?

**Comment by notanaverageman** [comment]
Seems that the change is new and there is no documentation for upgrading. I have asked in https://github.com/Fody/Fody/issues/511 how to update the packages correctly. When it is resolved, I can update the package.

**Comment by shinriyo** [comment]
I can't update the version too.

<img width="827" alt="screen shot 2018-04-02 at 23 04 25" src="https://user-images.githubusercontent.com/396927/38199125-64d3541a-36ca-11e8-9d64-0e3e5ee7e1b5.png">

```
Could not install package 'FodyHelpers 3.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by notanaverageman** [comment]
@shinriyo Your issue seems like something else. If I'm not wrong FodyHelpers requires `.NET Standard 2.0` while your project targets `.NETPortable,Version=v4.5,Profile=Profile78` which is .NET Standard 1.0. You should update your .NET target.

**Comment by notanaverageman** [comment]
0.5.0 is out with Fody 3.0. It should be indexed by Nuget in a few hours. Let me know if there is any problem.
